### PR TITLE
Allow Symfony 5

### PR DESCRIPTION
**Pull request by emodric**

### CODE REVIEW

**Review by lchrusciel — COMMENTED** [review]
Hey Edi! 

thanks for the contribution! Can you adjust the Travis suite as well? 

https://github.com/FriendsOfBehat/VariadicExtension/blob/master/.travis.yml#L8-L11

I think we should test Symfony versions 3.4, 4.4 and 5.0

**Comment by emodric** [comment]
Done!

**Comment by pamil** [comment]
Symfony 5.0 is not supported by Behat itself yet, need to wait for that first.

**Comment by emodric** [comment]
No problem! I created the PR so its ready when needed :)

**Comment by emodric** [comment]
@pamil Behat now has support for Symfony 5. Do you think you can reevaluate this PR now?

**Comment by emodric** [comment]
Looks like Symfony 5 requires PHP 7.2.5. How would you like to handle this? Do I simply remove the combination from  the test matrix or do we bump the PHP version in `composer.json` ?

**Comment by lchrusciel** [comment]
I would say, that we need both ;)

**Comment by emodric** [comment]
How about this? Should be ok now.

**Review by lchrusciel — APPROVED** [review]

**Comment by lchrusciel** [comment]
Thank you, Edi! :1st_place_medal:

**Comment by lchrusciel** [comment]
Let's see, if we can add support for PHP 7.4 as well and I will tag the next version

**Comment by lchrusciel** [comment]
And it's there: https://github.com/FriendsOfBehat/VariadicExtension/releases/tag/v1.3.0

**Comment by emodric** [comment]
Thanks @lchrusciel ! :tada:

**Pull request merged**
